# Generated by Django 5.2.8 on 2025-12-17 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BanThietKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_url', models.URLField(max_length=500, verbose_name='Link ảnh thiết kế')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú/Yêu cầu')),
                ('phan_hoi_admin', models.TextField(blank=True, null=True, verbose_name='Phản hồi Admin')),
                ('trang_thai', models.CharField(choices=[('BO_SUU_TAP', 'Lưu bộ sưu tập riêng'), ('CHO_XET_DUYET', 'Gửi yêu cầu gia công'), ('XAC_NHAN_GIA_CONG', 'Xác nhận gia công'), ('TU_CHOI', 'Từ chối')], default='BO_SUU_TAP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoi_so_huu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thiet_ke_so_huu', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('tong_chi_tieu', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ngay_tham_gia', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(max_length=20, unique=True)),
                ('loai_hoa_don', models.CharField(choices=[('ONLINE', 'Web Online'), ('OFFLINE', 'Tại quầy')], default='ONLINE', max_length=10)),
                ('trang_thai', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_XAC_NHAN', 'Đã xác nhận/Đóng gói'), ('DANG_GIAO', 'Đang vận chuyển'), ('HOAN_THANH', 'Đã hoàn thành'), ('DA_HUY', 'Đã hủy')], default='CHO_XAC_NHAN', max_length=20)),
                ('phuong_thuc_tt', models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('CK', 'Chuyển khoản ngân hàng'), ('TIEN_MAT', 'Tiền mặt (Tại quầy)')], default='COD', max_length=20)),
                ('ho_ten_nguoi_nhan', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt_nguoi_nhan', models.CharField(blank=True, max_length=15, null=True)),
                ('dia_chi_giao_hang', models.TextField(blank=True, null=True)),
                ('tong_tien_hang', models.DecimalField(decimal_places=0, max_digits=15)),
                ('giam_gia', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='TuiXach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tui', models.CharField(max_length=250)),
                ('mo_ta', models.TextField(blank=True)),
                ('gia_tien', models.DecimalField(decimal_places=0, max_digits=12)),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('hinh_anh', models.CharField(max_length=800)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_tui_xach', to='api.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('don_gia_luc_ban', models.DecimalField(decimal_places=0, max_digits=12)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='api.hoadon')),
                ('tui_xach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tuixach')),
            ],
        ),
    ]
